<?php

namespace App\Models\Backend\UserManagement;

use App\Models\Backend\Course\Course;
use App\Models\Scopes\Searchable;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Teacher extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'user_id',
        'first_name',
        'last_name',
        'email',
        'mobile',
        'image',
        'teacher_intro_video',
        'teacher_intro_banner',
        'demo_video_1',
        'demo_banner_1',
        'demo_video_2',
        'demo_banner_2',
        'description',
        'present_address',
        'permanent_address',
        'subject',
        'last_education',
        'total_commission',
        'status',
        'github',
        'twitter',
        'linkedin',
        'whatsapp',
        'facebook',
        'website',
        'dob',
        'gender',
    ];

    protected $searchableFields = ['*'];

    protected static $student;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($teacher){
            if (!empty($teacher->courses))
            {
                $teacher->courses()->detach();
            }
            if (!empty($teacher->batchExams))
            {
                $teacher->batchExams()->detach();
            }
        });
    }

    public static function createOrUpdateTeacher ($request, $user = null, $id = null)
    {

        // if (isset($request->teacher_intro_video)) {
        //     # code...
        //     if ($request->teacher_intro_video != 'https://youtu.be/') {
        //         # code...
        //         $check = 1;
        //     }else {
        //         # code...
        //         $check=0;
        //     }
        // }else {
        //     # code...
        //     $check=0;
        // }


        Teacher::updateOrCreate(['id' => $id], [
            'user_id'                   => $user->id,
            'first_name'                => $request->first_name,
            'last_name'                 => $request->last_name,
            'email'                     => $request->email,
            'mobile'                    => $request->mobile,
            'image'                     => imageUpload($request->file('image'), 'student-images/', 'student', '280', '350', (isset($id) ? static::find($id)->image : null)),
            'teacher_intro_banner'      => imageUpload($request->file('teacher_intro_banner'), 'student-images/', 'student', '280', '350', (isset($id) ? static::find($id)->teacher_intro_banner : null)),
            'teacher_intro_video'       => $request->teacher_intro_video,
            // 'teacher_intro_video'                 => $check == 1 ? explode('https://www.youtube.com/watch?v=', $request->teacher_intro_video)[1] : '',

            // 'teacher_intro_video'       => fileUpload($request->file('teacher_intro_video'),'additional-feature-management/our-team/teacher-video', 'our-team-video', isset($id) ? static::find($id)->teacher_intro_video : ''),
            
            'demo_video_1'              => $request->demo_video_1,
            'demo_banner_1'             => imageUpload($request->file('demo_banner_1'), 'student-images/', 'student', '280', '350', (isset($id) ? static::find($id)->demo_banner_1 : null)),

            // 'demo_video_1'              => fileUpload($request->file('demo_video_1'),'additional-feature-management/our-team/teacher-video', 'our-team-video', isset($id) ? static::find($id)->demo_video_1 : ''),
            'demo_video_2'              => $request->demo_video_2,
            'demo_banner_2'             => imageUpload($request->file('demo_banner_2'), 'student-images/', 'student', '280', '350', (isset($id) ? static::find($id)->demo_banner_2 : null)),

            // 'demo_video_2'              => fileUpload($request->file('demo_video_2'),'additional-feature-management/our-team/teacher-video', 'our-team-video', isset($id) ? static::find($id)->demo_video_2 : ''),
            'description'               => $request->description,
            'subject'                   => $request->subject,
            'present_address'           => $request->present_address,
            'permanent_address'         => $request->permanent_address,
            'last_education'            => $request->last_education,
            'github'                    => $request->github,
            'twitter'                   => $request->twitter,
            'linkedin'                  => $request->linkedin,
            'whatsapp'                  => $request->whatsapp,
            'facebook'                  => $request->facebook,
            'website'                   => $request->website,
            'dob'                       => $request->dob,
            'gender'                   => $request->gender,
//            'status'                    => $request->status,
        ]);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }
}
